name: Test

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test no defualt features
        run: |
          nix develop -c cargo run --no-default-features --example instance
          nix develop -c cargo run --no-default-features --example diff
          nix develop -c cargo run --no-default-features --example json
          nix develop -c cargo run --no-default-features --example rename-patch-struct
          nix develop -c cargo run --no-default-features --example patch-attr
          nix develop -c cargo test --no-default-features

      - name: Test with default features
        run: |
          nix develop -c cargo run --example status
          nix develop -c cargo test

      - name: Test add feature
        run: |
          nix develop -c cargo run --features=add --example instance
          nix develop -c cargo run --features=add --example diff
          nix develop -c cargo run --features=add --example json
          nix develop -c cargo run --features=add --example rename-patch-struct
          nix develop -c cargo run --features=add --example patch-attr
          nix develop -c cargo test --features=add
